// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs8zGYhS6_qI-MrRPzonALGLG0Za9PtFc',
    appId: '1:208667789254:web:e9712aa49215c46cfd94c7',
    messagingSenderId: '208667789254',
    projectId: 'parkpal-assignment',
    authDomain: 'parkpal-assignment.firebaseapp.com',
    storageBucket: 'parkpal-assignment.firebasestorage.app',
    measurementId: 'G-DEZ5E66VZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzYTZTETWRD-mflgHO8Tsu4oq1aEE_ge4',
    appId: '1:208667789254:android:101811483707c588fd94c7',
    messagingSenderId: '208667789254',
    projectId: 'parkpal-assignment',
    storageBucket: 'parkpal-assignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANMY4I2RYWaGaysxR6Usz5SclIoBnMx7U',
    appId: '1:208667789254:ios:53bd2224fafa7355fd94c7',
    messagingSenderId: '208667789254',
    projectId: 'parkpal-assignment',
    storageBucket: 'parkpal-assignment.firebasestorage.app',
    iosBundleId: 'com.example.parkpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANMY4I2RYWaGaysxR6Usz5SclIoBnMx7U',
    appId: '1:208667789254:ios:53bd2224fafa7355fd94c7',
    messagingSenderId: '208667789254',
    projectId: 'parkpal-assignment',
    storageBucket: 'parkpal-assignment.firebasestorage.app',
    iosBundleId: 'com.example.parkpal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs8zGYhS6_qI-MrRPzonALGLG0Za9PtFc',
    appId: '1:208667789254:web:73e292393a9a06e5fd94c7',
    messagingSenderId: '208667789254',
    projectId: 'parkpal-assignment',
    authDomain: 'parkpal-assignment.firebaseapp.com',
    storageBucket: 'parkpal-assignment.firebasestorage.app',
    measurementId: 'G-TQFLRNY2FJ',
  );
}
